// Self-contained type declarations for Molcajete v2 hooks.
// Generated by `molcajete setup` — safe to edit.

/** Key-value store scoped to a lifecycle phase (plan, task, subtask). */
export interface ScopedStore {
  get<T = unknown>(key: string): T | undefined;
  set(key: string, value: unknown): void;
  has(key: string): boolean;
  delete(key: string): boolean;
  keys(): string[];
  entries(): Array<[string, unknown]>;
  clear(): void;
}

/** Describes a host environment (local or remote) for test execution. */
export interface HostDescriptor {
  name: string;
  type: 'local' | 'remote';
  path?: string;
  ssh?: { host: string; port: number; user: string; keyPath?: string };
  appPath?: string;
  metadata?: Record<string, unknown>;
}

/** Task-scoped store with host registration. */
export interface TaskStore extends ScopedStore {
  registerHost(descriptor: HostDescriptor): void;
  getHost(name?: string): HostDescriptor | undefined;
  getHosts(): HostDescriptor[];
  removeHost(name: string): boolean;
}

/** Information about the current Molcajete instance. */
export interface InstanceInfo {
  cwd: string;
  planId: string;
  pid: number;
  id: string;
}

/** Information about the hook being executed. */
export interface HookInfo {
  name: string;
  taskId?: string;
  subtaskId?: string;
  worktreePath?: string;
  branch?: string;
  identifiers?: Record<string, string>;
}

/** Global cross-instance registry interface. */
export interface GlobalRegistry {
  get<T = unknown>(key: string): T | undefined;
  set(key: string, value: unknown): Promise<void>;
  has(key: string): boolean;
  listInstances(): InstanceInfo[];
  allocatePort(startFrom?: number): Promise<number>;
  connect(): Promise<void>;
  disconnect(): void;
}

/** Serializable subset of context for Claude session prompts. */
export interface ContextSnapshot {
  planId: string;
  taskId?: string;
  subtaskId?: string;
  planStore: Record<string, unknown>;
  taskStore: Record<string, unknown>;
  hosts: HostDescriptor[];
}

/** Context object passed to v2 hook functions. */
export interface HookContext<TInput = Record<string, unknown>> {
  input: TInput;
  plan: ScopedStore;
  task: TaskStore;
  subtask: ScopedStore;
  global: GlobalRegistry;
  instance: InstanceInfo;
  hook: HookInfo;
  getHost(name?: string): HostDescriptor | undefined;
  getHosts(): HostDescriptor[];
  getHostPort(internalPort: number): number | undefined;
  snapshot(): ContextSnapshot;
}

// ── Per-Hook Input/Output Types ──

/** Shared identifiers included in hook inputs. */
export interface HookIdentifiers {
  task_id: string;
  feature_id?: string;
  usecase_id?: string;
  scenario_id?: string;
}

// ── Mandatory Hooks ──

export interface HealthCheckInput {
  services?: string[];
}
export interface HealthCheckOutput {
  status: 'ready' | 'failed';
  services: Record<string, 'ready' | 'failed'>;
}

export interface RunTestsInput extends HookIdentifiers {
  tags?: string[];
  scope?: 'task' | 'preflight' | 'final';
}
export interface RunTestsOutput {
  status: 'pass' | 'fail' | 'error';
  failures?: string[];
  summary: string;
}

export interface FormatInput extends HookIdentifiers {
  files?: string[];
  services?: string[];
}
export interface FormatOutput {
  status: 'pass' | 'fail';
  issues: string[];
}

export interface LintInput extends HookIdentifiers {
  files?: string[];
  services?: string[];
}
export interface LintOutput {
  status: 'pass' | 'fail';
  issues: string[];
}

// ── Environment Hooks ──

export type StartInput = Record<string, never>;
export interface StartOutput {
  status: 'ready' | 'failed';
  summary?: string;
}

export type StopInput = Record<string, never>;
export interface StopOutput {
  status: 'ok' | 'failed';
  summary?: string;
}

export interface LogsInput {
  service?: string;
  lines?: number;
  since?: string;
}
export interface LogsOutput {
  logs: string;
}

export type RestartInput = Record<string, never>;
export interface RestartOutput {
  status: 'ready' | 'failed';
}

// ── Worktree Hooks ──

export interface CreateWorktreeInput {
  path: string;
  branch: string;
  base_branch: string;
}
export interface CreateWorktreeOutput {
  status: 'ok' | 'failed';
  path: string;
}

export interface CleanupInput {
  path: string;
  branch: string;
}
export interface CleanupOutput {
  status: 'ok' | 'failed';
}

export interface MergeInput {
  path: string;
  branch: string;
  base_branch: string;
}
export interface MergeOutput {
  status: 'ok' | 'failed';
  conflicts?: string[];
}

// ── Lifecycle Hooks ──

export interface TaskLifecycleInput extends HookIdentifiers {
  status?: string;
  summary?: string;
}

export interface SubtaskLifecycleInput extends HookIdentifiers {
  subtask_id: string;
  status?: string;
}

export interface CommitLifecycleInput extends HookIdentifiers {
  commits?: string[];
  files?: string[];
  base_branch?: string;
  working_branch?: string;
}

export interface ValidateLifecycleInput extends HookIdentifiers {
  cycle: number;
}

export interface WorktreeLifecycleInput extends HookIdentifiers {
  path?: string;
  branch?: string;
  base_branch?: string;
}

export interface LifecycleOutput {
  status: 'ok';
}
